// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: proto/metrics.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Metrics_CounterInc_FullMethodName = "/musthave_metrics.Metrics/CounterInc"
	Metrics_CounterGet_FullMethodName = "/musthave_metrics.Metrics/CounterGet"
	Metrics_GaugeSet_FullMethodName   = "/musthave_metrics.Metrics/GaugeSet"
	Metrics_GaugeGet_FullMethodName   = "/musthave_metrics.Metrics/GaugeGet"
)

// MetricsClient is the client API for Metrics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricsClient interface {
	CounterInc(ctx context.Context, in *CounterIncRequest, opts ...grpc.CallOption) (*CounterIncResponse, error)
	CounterGet(ctx context.Context, in *CounterGetRequest, opts ...grpc.CallOption) (*CounterGetResponse, error)
	GaugeSet(ctx context.Context, in *GaugeSetRequest, opts ...grpc.CallOption) (*GaugeSetResponse, error)
	GaugeGet(ctx context.Context, in *GaugeGetRequest, opts ...grpc.CallOption) (*GaugeGetResponse, error)
}

type metricsClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsClient(cc grpc.ClientConnInterface) MetricsClient {
	return &metricsClient{cc}
}

func (c *metricsClient) CounterInc(ctx context.Context, in *CounterIncRequest, opts ...grpc.CallOption) (*CounterIncResponse, error) {
	out := new(CounterIncResponse)
	err := c.cc.Invoke(ctx, Metrics_CounterInc_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) CounterGet(ctx context.Context, in *CounterGetRequest, opts ...grpc.CallOption) (*CounterGetResponse, error) {
	out := new(CounterGetResponse)
	err := c.cc.Invoke(ctx, Metrics_CounterGet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) GaugeSet(ctx context.Context, in *GaugeSetRequest, opts ...grpc.CallOption) (*GaugeSetResponse, error) {
	out := new(GaugeSetResponse)
	err := c.cc.Invoke(ctx, Metrics_GaugeSet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) GaugeGet(ctx context.Context, in *GaugeGetRequest, opts ...grpc.CallOption) (*GaugeGetResponse, error) {
	out := new(GaugeGetResponse)
	err := c.cc.Invoke(ctx, Metrics_GaugeGet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsServer is the server API for Metrics service.
// All implementations must embed UnimplementedMetricsServer
// for forward compatibility
type MetricsServer interface {
	CounterInc(context.Context, *CounterIncRequest) (*CounterIncResponse, error)
	CounterGet(context.Context, *CounterGetRequest) (*CounterGetResponse, error)
	GaugeSet(context.Context, *GaugeSetRequest) (*GaugeSetResponse, error)
	GaugeGet(context.Context, *GaugeGetRequest) (*GaugeGetResponse, error)
	mustEmbedUnimplementedMetricsServer()
}

// UnimplementedMetricsServer must be embedded to have forward compatible implementations.
type UnimplementedMetricsServer struct {
}

func (UnimplementedMetricsServer) CounterInc(context.Context, *CounterIncRequest) (*CounterIncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CounterInc not implemented")
}
func (UnimplementedMetricsServer) CounterGet(context.Context, *CounterGetRequest) (*CounterGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CounterGet not implemented")
}
func (UnimplementedMetricsServer) GaugeSet(context.Context, *GaugeSetRequest) (*GaugeSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GaugeSet not implemented")
}
func (UnimplementedMetricsServer) GaugeGet(context.Context, *GaugeGetRequest) (*GaugeGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GaugeGet not implemented")
}
func (UnimplementedMetricsServer) mustEmbedUnimplementedMetricsServer() {}

// UnsafeMetricsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsServer will
// result in compilation errors.
type UnsafeMetricsServer interface {
	mustEmbedUnimplementedMetricsServer()
}

func RegisterMetricsServer(s grpc.ServiceRegistrar, srv MetricsServer) {
	s.RegisterService(&Metrics_ServiceDesc, srv)
}

func _Metrics_CounterInc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CounterIncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).CounterInc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metrics_CounterInc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).CounterInc(ctx, req.(*CounterIncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_CounterGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CounterGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).CounterGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metrics_CounterGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).CounterGet(ctx, req.(*CounterGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_GaugeSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GaugeSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).GaugeSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metrics_GaugeSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).GaugeSet(ctx, req.(*GaugeSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_GaugeGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GaugeGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).GaugeGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metrics_GaugeGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).GaugeGet(ctx, req.(*GaugeGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Metrics_ServiceDesc is the grpc.ServiceDesc for Metrics service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Metrics_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "musthave_metrics.Metrics",
	HandlerType: (*MetricsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CounterInc",
			Handler:    _Metrics_CounterInc_Handler,
		},
		{
			MethodName: "CounterGet",
			Handler:    _Metrics_CounterGet_Handler,
		},
		{
			MethodName: "GaugeSet",
			Handler:    _Metrics_GaugeSet_Handler,
		},
		{
			MethodName: "GaugeGet",
			Handler:    _Metrics_GaugeGet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/metrics.proto",
}
