name: go vet test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  static_lint:
    runs-on: ubuntu-latest
    container: golang:1.21
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build staticlint
        run: |
          go build -buildvcs=false -o staticlint ./cmd/staticlint/

      - name: Run staticlint
        continue-on-error: true
        run: |
          ./staticlint ./...
